# Generated by Django 6.0.3 on 2026-03-14 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('album_type', models.CharField(choices=[('album', 'Album'), ('ep', 'EP'), ('single', 'Single'), ('compilation', 'Compilation'), ('soundtrack', 'Soundtrack')], default='album', max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-release_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('file_hash', models.CharField(help_text='SHA-256 hash of audio file for deduplication', max_length=64, unique=True)),
                ('lyrics', models.TextField(blank=True)),
                ('artwork_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_artist_name_43b0c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlbumArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
            ],
            options={
                'verbose_name': 'Album Artist',
                'verbose_name_plural': 'Album Artists',
                'unique_together': {('album', 'artist')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(through='core.AlbumArtist', to='core.artist'),
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('song', 'Song'), ('album', 'Album'), ('artist', 'Artist')], max_length=20)),
                ('model_id', models.IntegerField(help_text='ID of the Song, Album, or Artist being modified')),
                ('field_name', models.CharField(help_text='Name of the field being changed', max_length=255)),
                ('old_value', models.TextField(blank=True, help_text='Current value of the field')),
                ('new_value', models.TextField(help_text='Proposed new value')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Moderator comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.song')),
            ],
            options={
                'verbose_name': 'Song Album',
                'verbose_name_plural': 'Song Albums',
                'ordering': ['album', 'track_number'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(through='core.SongAlbum', to='core.album'),
        ),
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Main Artist'), ('featured', 'Featured Artist'), ('producer', 'Producer'), ('writer', 'Writer'), ('composer', 'Composer')], default='main', max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.song')),
            ],
            options={
                'verbose_name': 'Song Artist',
                'verbose_name_plural': 'Song Artists',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(through='core.SongArtist', to='core.artist'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('general', 'General User'), ('moderator', 'Moderator'), ('owner', 'Owner')], default='general', max_length=20)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['title'], name='core_album_title_79589d_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['release_date'], name='core_album_release_e021d0_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['status', 'created_at'], name='core_change_status_6a49fb_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['model_type', 'model_id'], name='core_change_model_t_aaec92_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['user', 'created_at'], name='core_change_user_id_a9c7f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='songalbum',
            unique_together={('song', 'album')},
        ),
        migrations.AlterUniqueTogether(
            name='songartist',
            unique_together={('song', 'artist', 'role')},
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='core_song_title_d4cb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['file_hash'], name='core_song_file_ha_1fab82_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='core_userpr_role_ce56eb_idx'),
        ),
    ]
