# Generated by Django 4.2.7 on 2026-03-20 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='albums', through='core.AlbumArtist', to='core.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(related_name='songs', through='core.SongAlbum', to='core.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', through='core.SongArtist', to='core.artist'),
        ),
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_libraries', to='core.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'added_at'], name='core_userso_user_id_a6dd02_idx')],
                'unique_together': {('user', 'song')},
            },
        ),
    ]
